-- Deploy tournament_sqitch:v2 to pg

BEGIN;

-- applique le format jour-mois-année par defaut pour le type DATE
ALTER DATABASE "d4e528emrou64t" SET DATESTYLE TO "ISO, DMY";

-- verifie qu'un email soit valide
ALTER TABLE "user" ADD CONSTRAINT "user_email_check"
    CHECK("email" ~ '^[\w\-\.]+@([\w-]+\.)+[\w-]{2,6}$');
ALTER TABLE "club" ADD CONSTRAINT "club_email_check"
    CHECK("email" ~ '^[\w\-\.]+@([\w-]+\.)+[\w-]{2,6}$');

-- verifie qu'un téléphone est valide
ALTER TABLE "club" ADD CONSTRAINT "club_phone_check"
    CHECK("phone" ~ '^\d{10}$');

-- ajout d'une table pour gerer les resultats
CREATE TABLE IF NOT EXISTS "result"(
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "label" TEXT NOT NULL UNIQUE
);

-- ajout d'un table pour gerer les genre
CREATE TABLE IF NOT EXISTS "gender"(
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "name" TEXT NOT NULL UNIQUE
);

ALTER TABLE "user" ADD COLUMN "phone" TEXT UNIQUE;
ALTER TABLE "user" ADD CONSTRAINT "user_phone_check"
    CHECK("phone" ~ '^\d{10}$');

-- Suppresion de la colonne gender et ajout de la FK gender_id
ALTER TABLE IF EXISTS "user" DROP COLUMN "gender" CASCADE;
ALTER TABLE IF EXISTS "user" ADD COLUMN "gender_id" INTEGER REFERENCES "gender"("id");

-- Suppresion de la colonne score et ajout de la FK result_id
ALTER TABLE IF EXISTS "match_has_team" DROP COLUMN "score" CASCADE;
ALTER TABLE IF EXISTS "match_has_team" ADD COLUMN "result_id" INTEGER REFERENCES "result"("id");

COMMIT;
