@hostname = http://localhost:3001/api/v1

###
# Get all matches
GET {{hostname}}/matches/ HTTP/1.1
content-type: application/json

###
# Get one match
GET {{hostname}}/matches/10 HTTP/1.1
content-type: application/json

###
# Create one match
POST {{hostname}}/matches/ HTTP/1.1
content-type: application/json

{
  "tournament_id": 5,
  "team_ids": [6,7]
}

###
# Update one match
PATCH {{hostname}}/matches/17 HTTP/1.1
content-type: application/json

{
  "note": "Une noteuh",
  "state_id": 4
}

###
# Add one team into match
PATCH {{hostname}}/matches/17/add-team HTTP/1.1
content-type: application/json

{
  "team_id": 4
}

###
# Remove one team from match
PATCH {{hostname}}/matches/17/remove-team HTTP/1.1
content-type: application/json

{
  "team_id": 4
}

###
# Delete one match
DELETE {{hostname}}/matches/18 HTTP/1.1
content-type: application/json
