@hostname = http://localhost:3001/api/v1

###
# Get all teams
GET {{hostname}}/teams/ HTTP/1.1
content-type: application/json

###
# Get one team
GET {{hostname}}/teams/10 HTTP/1.1
content-type: application/json

###
# Create one team
POST {{hostname}}/teams/ HTTP/1.1
content-type: application/json

{
  "tournament_id": 5,
  "user_ids": [6,7]
}

###
# Delete one match
DELETE {{hostname}}/teams/16 HTTP/1.1
content-type: application/json
